### model
model_name_or_path: D:\04.Code\model\Qwen2.5-1.5B
adapter_name_or_path: D:\06.学习资料\llm course\Basic-LLM-Learning\Code\LLM03\output\qwen1.5b_gsm8k_full_llamafactory
template: qwen
finetuning_type: lora

### export
export_dir: D:\04.Code\model\Qwen2.5-1.5B-lora-sft
export_size: 1
export_device: cpu
export_legacy_format: false